import { useEffect, useMemo, useRef, useState } from "react";
import { useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  api,
  type Chapter,
  type MemoryEntry,
  type MemoryEntryCreate,
  type MemoryKind,
  type MemoryVisibility,
  type Project,
} from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "@/components/ui/toast";

// 초안 추가 폼에서 작가가 직접 만드는 종류 — 롤업 층은 job이 생성한다.
const KINDS: Array<{ value: MemoryKind; label: string }> = [
  { value: "summary", label: "요약" },
  { value: "beat", label: "비트" },
  { value: "decision", label: "결정" },
  { value: "fact", label: "사실" },
  { value: "timeline", label: "시간축" },
  { value: "relationship_note", label: "관계 메모" },
];

// 표시·필터용 전체 종류 (자동 생성 층 포함)
const ALL_KINDS: Array<{ value: MemoryKind; label: string }> = [
  ...KINDS,
  { value: "arc_summary", label: "아크 요약" },
  { value: "volume_memory", label: "권 기억" },
];

const VISIBILITIES: Array<{ value: MemoryVisibility; label: string }> = [
  { value: "draft", label: "초안" },
  { value: "approved", label: "승인" },
  { value: "retired", label: "폐기" },
];

function optionalNumber(value: string): number | null {
  if (!value.trim()) return null;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function memoryLabel(kind: MemoryKind): string {
  return ALL_KINDS.find((item) => item.value === kind)?.label ?? kind;
}

function isAutoGenerated(memory: MemoryEntry): boolean {
  return memory.provenance?.generated_by === "summary-worker";
}

function visibilityClass(visibility: MemoryVisibility): string {
  if (visibility === "approved") return "text-success";
  if (visibility === "retired") return "text-muted-foreground";
  return "text-warning";
}

const PROVENANCE_DISPLAY_KEYS = [
  "generated_by",
  "job_id",
  "prompt_version",
  "model_snapshot",
  "arc_size",
  "volume_size",
];

function provenanceLabel(provenance: Record<string, unknown>): string {
  const pairs = PROVENANCE_DISPLAY_KEYS.filter((key) =>
    ["string", "number", "boolean"].includes(typeof provenance[key]),
  ).map((key) => `${key}: ${String(provenance[key])}`);
  return pairs.join(" · ") || "수동 입력";
}

function buildListPath(
  pid: number,
  filters: {
    kind: MemoryKind | "";
    visibility: MemoryVisibility | "";
    stale: "" | "true" | "false";
    chapterId: string;
  },
): string {
  const params = new URLSearchParams();
  if (filters.kind) params.set("kind", filters.kind);
  if (filters.visibility) params.set("visibility", filters.visibility);
  if (filters.stale) params.set("stale", filters.stale);
  if (filters.chapterId) params.set("chapter_id", filters.chapterId);
  const query = params.toString();
  return `/projects/${pid}/memories${query ? `?${query}` : ""}`;
}

interface SummaryJob {
  id: number;
  kind: string;
  status: string;
  attempt_count: number;
  error: string | null;
  source_sort_order: number;
}

interface SummaryJobPlanResult {
  summary: { created: number; duplicates: number };
  arc?: { created: number; duplicates: number } | null;
  volume?: { created: number; duplicates: number } | null;
}

interface SummaryJobRunResult {
  processed: SummaryJob[];
}

const JOB_STATUS_LABELS: Record<string, string> = {
  planned: "대기",
  running: "실행 중",
  draft_saved: "초안 저장",
  skipped_empty: "빈 원문 건너뜀",
  stale_source: "원문 변경됨",
  provider_error: "오류",
  rejected: "거절",
  duplicate_skipped: "중복 건너뜀",
};

const JOB_KIND_LABELS: Record<string, string> = {
  summary: "회차 요약",
  arc: "아크",
  volume: "권",
};

export function MemoryPage() {
  const { pid: rawPid } = useParams();
  return <ProjectMemoryPage key={rawPid} pid={Number(rawPid)} />;
}

function ProjectMemoryPage({ pid }: { pid: number }) {
  const mounted = useRef(false);
  useEffect(() => {
    mounted.current = true;
    return () => {
      mounted.current = false;
    };
  }, []);
  const queryClient = useQueryClient();
  const [kind, setKind] = useState<MemoryKind | "">("");
  const [visibility, setVisibility] = useState<MemoryVisibility | "">("");
  const [stale, setStale] = useState<"" | "true" | "false">("");
  const [chapterId, setChapterId] = useState("");
  const [origin, setOrigin] = useState<"" | "auto" | "manual">("");
  const [memoryKind, setMemoryKind] = useState<MemoryKind>("fact");
  const [body, setBody] = useState("");
  const [sourceChapter, setSourceChapter] = useState("");
  const [fromSortOrder, setFromSortOrder] = useState("");
  const [toSortOrder, setToSortOrder] = useState("");
  const [confirming, setConfirming] = useState<{
    id: number;
    targetVisibility: "approved" | "retired";
  } | null>(null);
  const confirmationRef = useRef<HTMLButtonElement>(null);
  const listRef = useRef<HTMLElement>(null);
  const [returnFocusTo, setReturnFocusTo] = useState<string | null>(null);

  const projectQuery = useQuery({
    queryKey: ["project", pid],
    queryFn: () => api.get<Project>(`/projects/${pid}`),
  });
  const chaptersQuery = useQuery({
    queryKey: ["chapters", pid],
    queryFn: () => api.get<Chapter[]>(`/projects/${pid}/chapters`),
  });
  const memoriesQuery = useQuery({
    queryKey: ["memories", pid, kind, visibility, stale, chapterId],
    queryFn: () =>
      api.get<MemoryEntry[]>(
        buildListPath(pid, { kind, visibility, stale, chapterId }),
      ),
  });
  const create = useMutation({
    mutationFn: ({ originPid, payload }: { originPid: number; payload: MemoryEntryCreate }) =>
      api.post<MemoryEntry>(`/projects/${originPid}/memories`, payload),
    onSuccess: (_, { originPid }) => {
      void queryClient.invalidateQueries({ queryKey: ["memories", originPid] });
      if (!mounted.current) return;
      setBody("");
      setSourceChapter("");
      setFromSortOrder("");
      setToSortOrder("");
      toast("장편 기억 초안을 추가했습니다.", "success");
    },
    onError: (error) => {
      if (mounted.current) toast(`기억 추가 실패: ${(error as Error).message}`, "error");
    },
  });
  const summaryJobsQuery = useQuery({
    queryKey: ["summary-jobs", pid],
    queryFn: () => api.get<SummaryJob[]>(`/projects/${pid}/summary-jobs`),
  });
  const invalidateSummary = async () => {
    await queryClient.invalidateQueries({ queryKey: ["summary-jobs", pid] });
    await queryClient.invalidateQueries({ queryKey: ["memories", pid] });
  };
  const planJobs = useMutation({
    mutationFn: () =>
      api.post<SummaryJobPlanResult>(`/projects/${pid}/summary-jobs/plan`, {}),
    onSuccess: async (result) => {
      await invalidateSummary();
      if (!mounted.current) return;
      const total =
        (result.summary?.created ?? 0) +
        (result.arc?.created ?? 0) +
        (result.volume?.created ?? 0);
      toast(
        total > 0
          ? `요약 잡 ${total}건을 계획했습니다.`
          : "새로 계획할 요약 잡이 없습니다.",
        "success",
      );
    },
    onError: (error) => {
      if (mounted.current)
        toast(`요약 잡 계획 실패: ${(error as Error).message}`, "error");
    },
  });
  const runJobs = useMutation({
    mutationFn: () =>
      api.post<SummaryJobRunResult>(
        `/projects/${pid}/summary-jobs/run?limit=10`,
      ),
    onSuccess: async (result) => {
      await invalidateSummary();
      if (!mounted.current) return;
      const saved = result.processed.filter(
        (j) => j.status === "draft_saved" || j.status === "duplicate_skipped",
      ).length;
      const failed = result.processed.filter(
        (j) => j.status === "provider_error" || j.status === "rejected",
      ).length;
      toast(
        `요약 잡 ${result.processed.length}건 처리 — 초안 ${saved}건` +
          (failed ? `, 실패 ${failed}건` : ""),
        failed ? "warning" : "success",
      );
    },
    onError: (error) => {
      if (mounted.current)
        toast(`요약 잡 실행 실패: ${(error as Error).message}`, "error");
    },
  });
  const retryJob = useMutation({
    mutationFn: (jobId: number) =>
      api.post<SummaryJob>(`/summary-jobs/${jobId}/retry`),
    onSuccess: invalidateSummary,
    onError: (error) => {
      if (mounted.current)
        toast(`재시도 실패: ${(error as Error).message}`, "error");
    },
  });

  const update = useMutation({
    mutationFn: ({
      originPid,
      id,
      patch,
    }: {
      originPid: number;
      id: number;
      patch: { visibility: MemoryVisibility };
    }) => api.patch<MemoryEntry>(`/projects/${originPid}/memories/${id}`, patch),
    onSuccess: async (_, { originPid, id, patch }) => {
      await queryClient.invalidateQueries({ queryKey: ["memories", originPid] });
      if (!mounted.current) return;
      setReturnFocusTo(`${id}:${patch.visibility}`);
      setConfirming(null);
      toast("장편 기억 상태를 변경했습니다.", "success");
    },
    onError: (error) => {
      if (mounted.current) toast(`기억 상태 변경 실패: ${(error as Error).message}`, "error");
    },
  });

  const chapters = chaptersQuery.data ?? [];
  const chapterTitleById = useMemo(
    () =>
      new Map(
        chapters.map((chapter) => [
          chapter.id,
          chapter.title.trim() || `${chapter.id}화`,
        ]),
      ),
    [chapters],
  );
  const memories = useMemo(() => {
    const rows = memoriesQuery.data ?? [];
    if (origin === "auto") return rows.filter(isAutoGenerated);
    if (origin === "manual") return rows.filter((m) => !isAutoGenerated(m));
    return rows;
  }, [memoriesQuery.data, origin]);

  useEffect(() => {
    if (confirming !== null) confirmationRef.current?.focus();
  }, [confirming]);

  useEffect(() => {
    if (!returnFocusTo || confirming || memoriesQuery.isFetching || !mounted.current) return;
    const trigger = listRef.current?.querySelector<HTMLButtonElement>(
      `button[data-memory-action="${returnFocusTo}"]:not(:disabled)`,
    );
    (trigger ?? listRef.current)?.focus();
    setReturnFocusTo(null);
  }, [returnFocusTo, confirming, memoriesQuery.isFetching]);

  const submit = () => {
    if (create.isPending) return;
    const trimmedBody = body.trim();
    const from = optionalNumber(fromSortOrder);
    const to = optionalNumber(toSortOrder);
    if (!trimmedBody) return;
    if (
      (fromSortOrder.trim() && from === null) ||
      (toSortOrder.trim() && to === null)
    ) {
      toast("적용 범위는 숫자로 입력하세요.", "error");
      return;
    }
    if (from !== null && to !== null && from > to) {
      toast("적용 시작 값은 종료 값보다 클 수 없습니다.", "error");
      return;
    }
    create.mutate({
      originPid: pid,
      payload: {
        kind: memoryKind,
        body: trimmedBody,
        chapter_id: sourceChapter ? Number(sourceChapter) : null,
        effective_from_sort_order: from,
        effective_to_sort_order: to,
      },
    });
  };

  return (
    <div className="mx-auto flex h-full max-w-[920px] flex-col gap-4 overflow-y-auto px-6 py-4">
      <header className="flex flex-wrap items-start gap-2">
        <div>
          <h1 className="text-lg font-semibold">장편 기억</h1>
          <p className="mt-1 text-xs text-muted-foreground">
            작품: {projectQuery.data?.title ?? (projectQuery.isError ? "불러오기 실패" : "불러오는 중…")}
          </p>
          {projectQuery.data?.synopsis && (
            <p className="mt-1 max-w-[680px] truncate text-xs text-muted-foreground">
              {projectQuery.data.synopsis}
            </p>
          )}
          <p className="mt-1 text-xs text-muted-foreground">
            원고를 바꾸지 않고, 작가가 직접 검토한 provenance 기억만 AI 집필에
            참고시킵니다.
          </p>
        </div>
        <Badge variant="secondary" className="ml-auto">
          {memories.length}건
        </Badge>
      </header>

      <section
        className="rounded-md border border-border p-3"
        aria-labelledby="summary-jobs-title"
      >
        <div className="flex flex-wrap items-center gap-2">
          <h2 id="summary-jobs-title" className="text-sm font-semibold">
            자동 요약 잡
          </h2>
          <div className="ml-auto flex gap-2">
            <Button
              variant="outline"
              size="sm"
              disabled={planJobs.isPending || runJobs.isPending}
              onClick={() => planJobs.mutate()}
            >
              {planJobs.isPending ? "계획 중…" : "요약 잡 계획"}
            </Button>
            <Button
              variant="outline"
              size="sm"
              disabled={planJobs.isPending || runJobs.isPending}
              onClick={() => runJobs.mutate()}
            >
              {runJobs.isPending ? "실행 중…" : "대기 잡 실행 (최대 10건)"}
            </Button>
          </div>
        </div>
        <p className="mt-1 text-xs text-muted-foreground">
          본문이 있는 회차의 요약·아크·권 잡을 계획하고 실행합니다. 결과는
          항상 초안으로 저장되며, 작가 승인 후에만 집필 컨텍스트에 들어갑니다.
        </p>
        {summaryJobsQuery.isError && (
          <p role="alert" className="mt-2 text-xs text-destructive">
            잡 목록을 불러오지 못했습니다.
          </p>
        )}
        {(summaryJobsQuery.data?.length ?? 0) > 0 && (
          <ul className="mt-2 space-y-1">
            {summaryJobsQuery.data!.map((job) => (
              <li
                key={job.id}
                className="flex items-center gap-2 text-xs text-muted-foreground"
              >
                <span className="font-mono">#{job.id}</span>
                <span>{JOB_KIND_LABELS[job.kind] ?? job.kind}</span>
                <span
                  className={
                    job.status === "provider_error"
                      ? "text-destructive"
                      : job.status === "draft_saved"
                        ? "text-success"
                        : undefined
                  }
                >
                  {JOB_STATUS_LABELS[job.status] ?? job.status}
                </span>
                {job.status === "provider_error" && (
                  <Button
                    variant="ghost"
                    size="sm"
                    className="h-5 px-1 text-xs"
                    disabled={retryJob.isPending}
                    onClick={() => retryJob.mutate(job.id)}
                  >
                    재시도
                  </Button>
                )}
                {job.error && (
                  <span className="truncate text-destructive/80" title={job.error}>
                    {job.error}
                  </span>
                )}
              </li>
            ))}
          </ul>
        )}
      </section>

      {[
        { label: "작품 정보", message: "작품 정보를 불러오지 못했습니다.", query: projectQuery },
        { label: "근거 회차 목록", message: "근거 회차 목록을 불러오지 못했습니다.", query: chaptersQuery },
        { label: "기억 목록", message: "기억 목록을 불러오지 못했습니다.", query: memoriesQuery },
      ].map(({ label, message, query }) => query.isError && (
        <div key={label} role="alert" className="flex items-center gap-2 text-sm text-destructive">
          <span>{message}</span>
          <Button variant="outline" size="sm" disabled={query.isFetching} onClick={() => void query.refetch()}>
            {label} 다시 시도
          </Button>
        </div>
      ))}

      <section
        className="rounded-md border border-border p-3"
        aria-labelledby="memory-create-title"
      >
        <h2 id="memory-create-title" className="mb-3 text-sm font-semibold">
          기억 초안 추가
        </h2>
        <div className="grid gap-3 md:grid-cols-2">
          <div>
            <Label htmlFor="memory-kind">종류</Label>
            <Select
              id="memory-kind"
              disabled={create.isPending}
              value={memoryKind}
              onChange={(event) =>
                setMemoryKind(event.target.value as MemoryKind)
              }
            >
              {KINDS.map((item) => (
                <option key={item.value} value={item.value}>
                  {item.label}
                </option>
              ))}
            </Select>
          </div>
          <div>
            <Label htmlFor="memory-source-chapter">근거 회차(선택)</Label>
            <Select
              id="memory-source-chapter"
              disabled={create.isPending}
              value={sourceChapter}
              onChange={(event) => setSourceChapter(event.target.value)}
            >
              <option value="">작품 전체 메모</option>
              {chapters.map((chapter) => (
                <option key={chapter.id} value={chapter.id}>
                  {chapterTitleById.get(chapter.id)}
                </option>
              ))}
            </Select>
          </div>
        </div>
        <Label htmlFor="memory-body" className="mt-3 block">
          내용
        </Label>
        <Textarea
          id="memory-body"
          disabled={create.isPending}
          rows={3}
          maxLength={20_000}
          placeholder="작가가 직접 확인할 사실·결정·요약을 입력하세요."
          value={body}
          onChange={(event) => setBody(event.target.value)}
        />
        <div className="mt-3 grid gap-3 md:grid-cols-[1fr_1fr_auto] md:items-end">
          <div>
            <Label htmlFor="memory-from">적용 시작 sort order</Label>
            <Input
              id="memory-from"
              disabled={create.isPending}
              inputMode="decimal"
              value={fromSortOrder}
              onChange={(event) => setFromSortOrder(event.target.value)}
            />
          </div>
          <div>
            <Label htmlFor="memory-to">적용 종료 sort order</Label>
            <Input
              id="memory-to"
              disabled={create.isPending}
              inputMode="decimal"
              value={toSortOrder}
              onChange={(event) => setToSortOrder(event.target.value)}
            />
          </div>
          <Button disabled={create.isPending || !body.trim()} onClick={submit}>
            {create.isPending ? "추가 중…" : "초안 추가"}
          </Button>
        </div>
        <p
          className="mt-2 text-[11px] text-muted-foreground"
          aria-live="polite"
        >
          저장 시 근거 회차의 현재 revision/hash는 서버가 계산하며, 새 기억은
          항상 초안으로 시작합니다.
        </p>
      </section>

      <section className="flex flex-wrap gap-2" aria-label="장편 기억 필터">
        <Select
          aria-label="기억 종류 필터"
          className="w-40"
          value={kind}
          onChange={(event) => setKind(event.target.value as MemoryKind | "")}
        >
          <option value="">모든 종류</option>
          {ALL_KINDS.map((item) => (
            <option key={item.value} value={item.value}>
              {item.label}
            </option>
          ))}
        </Select>
        <Select
          aria-label="생성 출처 필터"
          className="w-36"
          value={origin}
          onChange={(event) =>
            setOrigin(event.target.value as "" | "auto" | "manual")
          }
        >
          <option value="">모든 출처</option>
          <option value="auto">자동 생성만</option>
          <option value="manual">수동 입력만</option>
        </Select>
        <Select
          aria-label="기억 상태 필터"
          className="w-32"
          value={visibility}
          onChange={(event) =>
            setVisibility(event.target.value as MemoryVisibility | "")
          }
        >
          <option value="">모든 상태</option>
          {VISIBILITIES.map((item) => (
            <option key={item.value} value={item.value}>
              {item.label}
            </option>
          ))}
        </Select>
        <Select
          aria-label="stale 필터"
          className="w-36"
          value={stale}
          onChange={(event) =>
            setStale(event.target.value as "" | "true" | "false")
          }
        >
          <option value="">stale 전체</option>
          <option value="false">현재 원문과 일치</option>
          <option value="true">stale만</option>
        </Select>
        <Select
          aria-label="근거 회차 필터"
          className="w-44"
          value={chapterId}
          onChange={(event) => setChapterId(event.target.value)}
        >
          <option value="">모든 근거 회차</option>
          {chapters.map((chapter) => (
            <option key={chapter.id} value={chapter.id}>
              {chapterTitleById.get(chapter.id)}
            </option>
          ))}
        </Select>
      </section>

      {memoriesQuery.isPending && (
        <p className="text-sm text-muted-foreground">기억을 불러오는 중…</p>
      )}
      {memoriesQuery.isSuccess && memories.length === 0 && (
        <p className="rounded-md border border-dashed border-border p-6 text-center text-sm text-muted-foreground">
          조건에 맞는 장편 기억이 없습니다.
        </p>
      )}
      <section
        className="flex flex-col gap-2"
        aria-live="polite"
        aria-label="장편 기억 목록"
        ref={listRef}
        tabIndex={-1}
      >
        {memories.map((memory) => (
          <article
            key={memory.id}
            className="rounded-md border border-border p-3"
          >
            <div className="flex flex-wrap items-center gap-2">
              <Badge variant="secondary">{memoryLabel(memory.kind)}</Badge>
              {isAutoGenerated(memory) && (
                <Badge variant="outline">자동 생성</Badge>
              )}
              <span
                className={`text-xs font-semibold ${visibilityClass(memory.visibility)}`}
              >
                {
                  VISIBILITIES.find((item) => item.value === memory.visibility)
                    ?.label
                }
              </span>
              {memory.stale && (
                <Badge
                  variant="outline"
                  className="border-destructive/40 text-destructive"
                >
                  stale — 자동 주입 제외
                </Badge>
              )}
              <span className="ml-auto text-[11px] text-muted-foreground">
                #{memory.id}
              </span>
            </div>
            <p className="mt-2 whitespace-pre-wrap text-sm">{memory.body}</p>
            <div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-[11px] text-muted-foreground">
              <span>근거: {memory.source_chapter_title ?? "작품 전체"}</span>
              <span>revision: {memory.source_revision ?? "—"}</span>
              <span>hash: {memory.source_sha256.slice(0, 12)}…</span>
              <span>provenance: {provenanceLabel(memory.provenance)}</span>
              {(memory.effective_from_sort_order !== null ||
                memory.effective_to_sort_order !== null) && (
                <span>
                  범위: {memory.effective_from_sort_order ?? "—"} ~{" "}
                  {memory.effective_to_sort_order ?? "—"}
                </span>
              )}
            </div>
            {memory.stale && (
              <p className="mt-2 text-xs text-warning" role="status">
                원문 revision/hash가 달라져 자동 주입하지 않습니다. 새 원문 기준
                기억은 별도로 추가하세요.
              </p>
            )}
            {memory.visibility !== "retired" && (
              <div className="mt-3 flex flex-wrap items-center justify-end gap-2">
                {confirming?.id === memory.id ? (
                  <div
                    className="flex flex-wrap items-center gap-2"
                    role="group"
                    aria-label="장편 기억 상태 변경 확인"
                  >
                    <span className="text-xs text-muted-foreground">
                      {confirming.targetVisibility === "approved"
                        ? "이 기억을 승인할까요? 조건에 맞으면 AI 집필에 참고됩니다."
                        : "이 기억을 폐기할까요? AI 집필에 참고하지 않으며 다시 활성화할 수 없습니다."}
                    </span>
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={() => {
                        setReturnFocusTo(`${confirming.id}:${confirming.targetVisibility}`);
                        setConfirming(null);
                      }}
                    >
                      취소
                    </Button>
                    <Button
                      ref={confirmationRef}
                      size="sm"
                      variant={
                        confirming.targetVisibility === "approved"
                          ? "default"
                          : "destructive"
                      }
                      disabled={update.isPending}
                      onClick={() =>
                        update.mutate({
                          originPid: pid,
                          id: memory.id,
                          patch: {
                            visibility: confirming.targetVisibility,
                          },
                        })
                      }
                    >
                      확인
                    </Button>
                  </div>
                ) : (
                  <>
                    {memory.visibility === "draft" && (
                      <Button
                        size="sm"
                        variant="outline"
                        data-memory-action={`${memory.id}:approved`}
                        onClick={() =>
                          setConfirming({
                            id: memory.id,
                            targetVisibility: "approved",
                          })
                        }
                      >
                        승인
                      </Button>
                    )}
                    <Button
                      size="sm"
                      variant="ghost"
                      data-memory-action={`${memory.id}:retired`}
                      onClick={() =>
                        setConfirming({
                          id: memory.id,
                          targetVisibility: "retired",
                        })
                      }
                    >
                      폐기
                    </Button>
                  </>
                )}
              </div>
            )}
          </article>
        ))}
      </section>
    </div>
  );
}
